[phases.setup]
nixPkgs = ['nodejs_22', 'nodePackages.pnpm']

[phases.install]
cmds = ['pnpm install --frozen-lockfile']

[phases.build]
cmds = ['pnpm build']

[start]
cmd = 'node .output/server/index.mjs'

[variables]
NODE_ENV = "production"
NITRO_HOST = "0.0.0.0"
NITRO_PORT = "3000"
